/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import Controller.TelaPrincipalController;
import javax.swing.JFrame;
import View.TelaLogin;
/**
 *
 * @author Willy
 */
public class TelaPrincipal extends javax.swing.JFrame {

    boolean tempTelaAtiva = false;
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState( MAXIMIZED_BOTH );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagemLogoMenor = new javax.swing.JLabel();
        btClientes = new javax.swing.JButton();
        btPedidos = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        dpTelaInterna = new javax.swing.JDesktopPane();
        lbImagemBackground = new javax.swing.JLabel();
        mbBarraMenu = new javax.swing.JMenuBar();
        mSistema = new javax.swing.JMenu();
        miDeslogar = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        miAtalhos = new javax.swing.JMenuItem();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PharmaDelivery - Tela Principal");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagemLogoMenor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.png"))); // NOI18N
        getContentPane().add(lbImagemLogoMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 110));

        btClientes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clientes.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 160, 80));

        btPedidos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pedidos.png"))); // NOI18N
        btPedidos.setText("Pedidos");
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 160, 80));

        btProdutos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/produtos.png"))); // NOI18N
        btProdutos.setText("Produtos");
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(btProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 160, 80));

        dpTelaInterna.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(dpTelaInterna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1200, 780));

        lbImagemBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tema branco azul.jpg"))); // NOI18N
        lbImagemBackground.setText("jLabel2222");
        getContentPane().add(lbImagemBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 940));

        mSistema.setText("Sistema");

        miDeslogar.setText("Deslogar");
        miDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeslogarActionPerformed(evt);
            }
        });
        mSistema.add(miDeslogar);

        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mSistema.add(miSair);

        mbBarraMenu.add(mSistema);

        mAjuda.setText("Ajuda");
        mAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAjudaActionPerformed(evt);
            }
        });

        miAtalhos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        miAtalhos.setText("Atalhos");
        miAtalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtalhosActionPerformed(evt);
            }
        });
        mAjuda.add(miAtalhos);

        miSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mAjuda.add(miSobre);

        mbBarraMenu.add(mAjuda);

        setJMenuBar(mbBarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        TelaPrincipalController tPrincipalController = new TelaPrincipalController();
        tPrincipalController.botaoTelaProdutos(this.dpTelaInterna);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void mAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAjudaActionPerformed
        
    }//GEN-LAST:event_mAjudaActionPerformed

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Desenvolvido por Wilk Teixeira Lima. \nEstudante do Curso de Sistemas de Informação. \nFaculdade Joaquim Nabuco (FJN) \n\nTodos os direitos reservados. ", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miSobreActionPerformed

    private void miAtalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtalhosActionPerformed
        JOptionPane.showMessageDialog(null, "Atalhos: F11 \nSobre: F12", "Atalhos", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_miAtalhosActionPerformed

    private void miDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeslogarActionPerformed
        TelaPrincipalController tPrincipalController = new TelaPrincipalController();
        tPrincipalController.botaoDeslogar(this);
    }//GEN-LAST:event_miDeslogarActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        TelaPrincipalController tPrincipalController = new TelaPrincipalController();
        tPrincipalController.botaoTelaClientes(this.dpTelaInterna);
    }//GEN-LAST:event_btClientesActionPerformed

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        TelaPrincipalController tPrincipalController = new TelaPrincipalController();
        tPrincipalController.botaoTelaPedidos(this.dpTelaInterna);
    }//GEN-LAST:event_btProdutosActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        TelaPrincipalController tPrincipalController = new TelaPrincipalController();
        tPrincipalController.botaoSair();
    }//GEN-LAST:event_miSairActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btProdutos;
    private javax.swing.JDesktopPane dpTelaInterna;
    private javax.swing.JLabel lbImagemBackground;
    private javax.swing.JLabel lbImagemLogoMenor;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mSistema;
    private javax.swing.JMenuBar mbBarraMenu;
    private javax.swing.JMenuItem miAtalhos;
    private javax.swing.JMenuItem miDeslogar;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables

}
